### PR TITLE
Bumping version to 9.800

### PR DESCRIPTION
**Pull request by amirmasoudabdol**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Ok, I think I got it this time! 🤞

### CODE REVIEW

**Comment by amirmasoudabdol** [comment]
I'm not sure what's going wrong here. I think something goes wrong before the actual build but I'm not sure how to track it. Can anyone offer some help? 🙏

**Comment by amirmasoudabdol** [comment]
I am familiar with the Armadillo’s CMake and build process but I don’t exactly understand what’s happening with the `CMakeLists.patch`.

**Comment by henryiii** [comment]
I've been working with the author upstream to get this added as an option instead of a patch that has to be maintained. See https://gitlab.com/conradsnicta/armadillo-code/issues/139 . I'll try to open a PR with the upstream patch applied.

**Comment by henryiii** [comment]
Version (finally) updated in #18, thank you!

**Pull request closed without merging**
