### PR TITLE
Rebuild update (Python 3.7, GCC 7, R 3.5.1, openBLAS 0.3.3)

### PR DESCRIPTION
**Pull request by grlee77**
This pr is an update of #9 to use the current armadillo version from the master branch and update the conda-forge pinnings. If this PR is merged, #9 should be closed.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
@conda-forge-admin, please rerender

**Comment by grlee77** [comment]
Okay. this is finally working now.  Can you take a quick look @marcelotrevisani or @dirmeier?

I reverted the --as-needed change from 273be01 as it was not necessary. I did still need to use `-lblas -larpack` in the Makefile for the tests when I tested locally so I have left the change from 758efa8 in.  

If you merge this, please also close #9.

**Comment by dirmeier** [comment]
Hey @grlee77 , wow that's great. No changes needed from my side. Whats with
```
build:
  number: 1202
```

Did I miss something here? Thanks for solving this.
Cheers,
Simon

**Comment by grlee77** [comment]
The rebuilds with the new compilers have been adding 1000 to the current
build number.  When I updated the bot's PR I should have reset it to 1200
since I updated that PR to use 9.200.4. At this point I think we can just
leave it as is and reset the next time we update the version.

**Pull request merged**
